resume_videos = ["https://www.youtube.com/watch?v=oYcSzUiz8hg",
    "https://www.youtube.com/watch?v=dByIqqJi2aI",
    "https://www.youtube.com/watch?v=yEhh73GZwAI",
    "https://www.youtube.com/watch?v=qf4H_wIR088",
    "https://www.youtube.com/watch?v=BsC1JbzlKxs",
    "https://www.youtube.com/watch?v=GqzEC4ADAYo",
    "https://www.youtube.com/watch?v=DhmgaeCSZ3s",
    "https://www.youtube.com/watch?v=0kkKn6eICgA",
    "https://www.youtube.com/watch?v=FMCGSykSGZ4",
    "https://www.youtube.com/watch?v=qS-JGYMe4uU",
    "https://www.youtube.com/watch?v=8N3AzPfX6MQ",
    "https://www.youtube.com/watch?v=4_ItBwW8ndg",
    "https://www.youtube.com/watch?v=LZgAOhvkSOU",
    "https://www.youtube.com/watch?v=srhIMjrPxRQ",
    "https://www.youtube.com/watch?v=luu25Dr7sfE",
    "https://www.youtube.com/watch?v=66K_x7I4Czs",
    "https://www.youtube.com/watch?v=hNh3npRmlug",
    "https://www.youtube.com/watch?v=Z54k3E93x4A",
    "https://www.youtube.com/watch?v=fOCqUsue1YA",
    "https://www.youtube.com/watch?v=rzmAECvFJDQ",
    "https://www.youtube.com/watch?v=Zep2ArIbE0I",
    "https://www.youtube.com/watch?v=_bssDclDVDA",
    "https://www.youtube.com/watch?v=btLmje6SvWY",
    "https://www.youtube.com/watch?v=_WqMQTUgJDg",
    "https://www.youtube.com/watch?v=xVLmSm95bE0",
    "https://www.youtube.com/watch?v=SOfIdQ8xD9w",
    "https://www.youtube.com/watch?v=FlBUTi6kMl8",
    "https://www.youtube.com/watch?v=mFXVnM7kl2c",
    "https://www.youtube.com/watch?v=AGrSzUOauOk",
    "https://www.youtube.com/watch?v=gIlatQGK9G4",
    "https://www.youtube.com/watch?v=VZZG776Tc5c",
    "https://www.youtube.com/watch?v=WkJt54LZ2yo",
    "https://www.youtube.com/watch?v=pq8A1Q7LP90",
    "https://www.youtube.com/watch?v=ABJj3b85-w8",
    "https://www.youtube.com/watch?v=1wj35_aQZGs",
    "https://www.youtube.com/watch?v=YqILtoe8uHw",
    "https://www.youtube.com/watch?v=UUVQ18qq61g",
    "https://www.youtube.com/watch?v=xjgKaA5Q38U",
    "https://www.youtube.com/watch?v=qip8qrj9MLs",
    "https://www.youtube.com/watch?v=Br3RlzQ5H80",
    "https://www.youtube.com/watch?v=uQPjtIXtDCo",
    "https://www.youtube.com/watch?v=s3-TaokXEtY",
    "https://www.youtube.com/watch?v=imdr-tTFoKY",
    "https://www.youtube.com/watch?v=xdz1aoB0OD8",
    "https://www.youtube.com/watch?v=7OzJcwozGFc",
    "https://www.youtube.com/watch?v=BUQ-WFskp_A",
    "https://www.youtube.com/watch?v=eQ7Lr2UKGhY",
    "https://www.youtube.com/watch?v=1ZqdAJFNPfY"]

ds_course = [['Machine Learning Crash Course by Google [Free]', 'https://developers.google.com/machine-learning/crash-course'],
             ['Machine Learning A-Z by Udemy','https://www.udemy.com/course/machinelearning/'],
             ['Machine Learning by Andrew NG','https://www.coursera.org/learn/machine-learning'],
             ['Data Scientist Master Program of Simplilearn (IBM)','https://www.simplilearn.com/big-data-and-analytics/senior-data-scientist-masters-program-training'],
             ['Data Science Foundations: Fundamentals by LinkedIn','https://www.linkedin.com/learning/data-science-foundations-fundamentals-5'],
             ['Data Scientist with Python','https://www.datacamp.com/tracks/data-scientist-with-python'],
             ['Programming for Data Science with Python','https://www.udacity.com/course/programming-for-data-science-nanodegree--nd104'],
             ['Programming for Data Science with R','https://www.udacity.com/course/programming-for-data-science-nanodegree-with-R--nd118'],
             ['Introduction to Data Science','https://www.udacity.com/course/introduction-to-data-science--cd0017'],
             ['Intro to Machine Learning with TensorFlow','https://www.udacity.com/course/intro-to-machine-learning-with-tensorflow-nanodegree--nd230']]

web_course = [['Django Crash course [Free]','https://youtu.be/e1IyzVyrLSU'],
              ['Python and Django Full Stack Web Developer Bootcamp','https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp'],
              ['React Crash Course [Free]','https://youtu.be/Dorf8i6lCuk'],
              ['ReactJS Project Development Training','https://www.dotnettricks.com/training/masters-program/reactjs-certification-training'],
              ['Full Stack Web Developer - MEAN Stack','https://www.simplilearn.com/full-stack-web-developer-mean-stack-certification-training'],
              ['Node.js and Express.js [Free]','https://youtu.be/Oe421EPjeBE'],
              ['Flask: Develop Web Applications in Python','https://www.educative.io/courses/flask-develop-web-applications-in-python'],
              ['Full Stack Web Developer by Udacity','https://www.udacity.com/course/full-stack-web-developer-nanodegree--nd0044'],
              ['Front End Web Developer by Udacity','https://www.udacity.com/course/front-end-web-developer-nanodegree--nd0011'],
              ['Become a React Developer by Udacity','https://www.udacity.com/course/react-nanodegree--nd019']]

android_course = [['Android Development for Beginners [Free]','https://youtu.be/fis26HvvDII'],
                  ['Android App Development Specialization','https://www.coursera.org/specializations/android-app-development'],
                  ['Associate Android Developer Certification','https://grow.google/androiddev/#?modal_active=none'],
                  ['Become an Android Kotlin Developer by Udacity','https://www.udacity.com/course/android-kotlin-developer-nanodegree--nd940'],
                  ['Android Basics by Google','https://www.udacity.com/course/android-basics-nanodegree-by-google--nd803'],
                  ['The Complete Android Developer Course','https://www.udemy.com/course/complete-android-n-developer-course/'],
                  ['Building an Android App with Architecture Components','https://www.linkedin.com/learning/building-an-android-app-with-architecture-components'],
                  ['Android App Development Masterclass using Kotlin','https://www.udemy.com/course/android-oreo-kotlin-app-masterclass/'],
                  ['Flutter & Dart - The Complete Flutter App Development Course','https://www.udemy.com/course/flutter-dart-the-complete-flutter-app-development-course/'],
                  ['Flutter App Development Course [Free]','https://youtu.be/rZLR5olMR64']]

ios_course = [['IOS App Development by LinkedIn','https://www.linkedin.com/learning/subscription/topics/ios'],
              ['iOS & Swift - The Complete iOS App Development Bootcamp','https://www.udemy.com/course/ios-13-app-development-bootcamp/'],
              ['Become an iOS Developer','https://www.udacity.com/course/ios-developer-nanodegree--nd003'],
              ['iOS App Development with Swift Specialization','https://www.coursera.org/specializations/app-development'],
              ['Mobile App Development with Swift','https://www.edx.org/professional-certificate/curtinx-mobile-app-development-with-swift'],
              ['Swift Course by LinkedIn','https://www.linkedin.com/learning/subscription/topics/swift-2'],
              ['Objective-C Crash Course for Swift Developers','https://www.udemy.com/course/objectivec/'],
              ['Learn Swift by Codecademy','https://www.codecademy.com/learn/learn-swift'],
              ['Swift Tutorial - Full Course for Beginners [Free]','https://youtu.be/comQ1-x2a1Q'],
              ['Learn Swift Fast - [Free]','https://youtu.be/FcsY1YPBwzQ']]
uiux_course = [['Google UX Design Professional Certificate','https://www.coursera.org/professional-certificates/google-ux-design'],
               ['UI / UX Design Specialization','https://www.coursera.org/specializations/ui-ux-design'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['UX & Web Design Master Course: Strategy, Design, Development','https://www.udemy.com/course/ux-web-design-master-course-strategy-design-development/'],
               ['The Complete App Design Course - UX, UI and Design Thinking','https://www.udemy.com/course/the-complete-app-design-course-ux-and-ui-design/'],
               ['DESIGN RULES: Principles + Practices for Great UI Design','https://www.udemy.com/course/design-rules/'],
               ['Become a UX Designer by Udacity','https://www.udacity.com/course/ux-designer-nanodegree--nd578'],
               ['Adobe XD Tutorial: User Experience Design Course [Free]','https://youtu.be/68w2VwalD5w'],
               ['Adobe XD for Beginners [Free]','https://youtu.be/WEljsc2jorI'],
               ['Adobe XD in Simple Way','https://learnux.io/course/adobe-xd']]


interview_videos = [    "https://www.youtube.com/watch?v=7UlslIXHNsw",
    "https://www.youtube.com/watch?v=9N2S3JZffeg",
    "https://www.youtube.com/watch?v=sv-3crA1img",
    "https://www.youtube.com/watch?v=ePF1BjGWQ5Y",
    "https://www.youtube.com/watch?v=dPb1bg1mVLg",
    "https://www.youtube.com/watch?v=FSycYs8RpsA",
    "https://www.youtube.com/watch?v=XxB1BCuvu9A",
    "https://www.youtube.com/watch?v=SPItnWGCr8U",
    "https://www.youtube.com/watch?v=ddAmt_Z2qic",
    "https://www.youtube.com/watch?v=80KvFXJSohA",
    "https://www.youtube.com/watch?v=g4JWyqB5_BI",
    "https://www.youtube.com/watch?v=FWmuxvOgh6Q",
    "https://www.youtube.com/watch?v=ciIkiWwZnlc",
    "https://www.youtube.com/watch?v=sVsFfsAicE4",
    "https://www.youtube.com/watch?v=jE_yjejZYpE",
    "https://www.youtube.com/watch?v=kOQ53LUYGJg",
    "https://www.youtube.com/watch?v=TPJzCY7bDfA",
    "https://www.youtube.com/watch?v=9UDKf3prDDw",
    "https://www.youtube.com/watch?v=wkZnPUzIbMo",
    "https://www.youtube.com/watch?v=vTgMKzRbPos",
    "https://www.youtube.com/watch?v=3UwVrpwSzmU",
    "https://www.youtube.com/watch?v=mRVMEROCsRM",
    "https://www.youtube.com/watch?v=uqOEzFaPqok",
    "https://www.youtube.com/watch?v=eqZLGnVw-XM",
    "https://www.youtube.com/watch?v=PHV1dn4BS-4"]